version: "3"
services:
  # db:
  #   image: couchbase
  #   ports:
  #     - 8091:8091
  #     - 8092:8092
  #     - 8093:8093
  #     - 8094:8094
  #     - 11210:11210

  webapisample:
    build: .
    ports:
      - "5259:5259"
    environment:
      SERVICE_PORT: 5259

  # cs-dbm:
  #   build: ../fi-db-qry-svc
  #   depends_on:
  #     - db
  #   ports:
  #     - "8002:8002"
  #   environment:
  #     COM_COUCHBASE_DBHOST: db
